library(randomForest)
library(readr)
setwd("~/Documents/Kaggle/Handwritten Digits/")
datatrain<-read.csv("train.csv")
datatest<-read.csv("test.csv")
xt<-subset(datatrain,select=c(pixel0:pixel783))
yt<-factor(datatrain$label)
test<-randomForest(x=xt,y=yt,xtest=datatest)
predictions <- data.frame(ImageId=1:nrow(datatest), Label=levels(yt)[test$test$predicted])
write_csv(predictions, "predicteddigits.csv") 